/* eslint-disable */
// WARNING: Do not edit this file

const ebconfig = {
  "integration": "project-Chinese-Vocab-zJ6qvzHHvZDaetv78zDdJqNADRsdhAz6",
  "version": "2020-11-20"
}

export default ebconfig;